### ISSUE TITLE
Problems replicating

### ISSUE THREAD

**Issue by noevasher** [deltaepsilon/firebase-search#2]
I have done some testing with replication in Algolia.
I've had some problems with it. Here I explain what have been those tests and what are the problems I have had:

PROOF 1: I put the documents (one by one) directly into the FireBase console and they all replicate in Algolia. (Satisfactory test)

PROOF 2: I import a json file (with 10 documents) into the FireBase console and replicate only one document in Algolia. (Test NOT satisfactory, because the 10 documents must be replicated).

PROOF 3: documents (over 100,000) are inserted by reading them from the file (as in demo.js). The documents are being added to FireBase and Algolia but there comes a time when replication stops (in my case, only 9,512 documents are replicated). (Test NOT satisfactory)

I would like to know at least why Test 2 does not replicate all the documents read.

**Comment by deltaepsilon** [comment]
I may have fixed this. I'm uncertain what the cause would be. I had a bug a while ago, but I got it solved, so try the test again maybe?
