### ISSUE TITLE
Retry on conflict setting

### ISSUE THREAD

**Issue by Bonitis** [deltaepsilon/firebase-search#6]
I am trying to include a `retry_on_conflict` parameter to my configuration, but I'm not sure where that should go. I am mostly using `ensure` in the following way:

``` javascript
const db = admin.database();

const indexRef = db.ref(Constants.FIREBASE.LOCATIONS.INDEX);

const indexSearch = new FirebaseSearch(indexRef, {
   elasticsearch: elasticSearchConfig,
}, Constants.FIREBASE.LOCATIONS.INDEX);

indexSearch.elasticsearch.indices.ensure().then(() => {
   indexSearch.elasticsearch.firebase.start();
});
```

Is it something that could be added to the elasticsearch config, passed into `FirebaseSearch`, or passed into the `ensure()` function?

**Comment by deltaepsilon** [comment]
@Bonitis 

I haven't used Elasticsearch in a while, but it appears that retryOnConflict is a parameter for elasticsearch.update: [ElasticSearch 5.0 API Update](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-update)

It looks like I need to add more options to firebase-search so you can pass additional create/update/delete parameters. [firebase-search.js:267](https://github.com/deltaepsilon/firebase-search/blob/master/firebase-search.js#L267) is where those extra params would need to be attached to the main update params.

You're welcome to make a pull request :) 

It's probably just a few lines of code plus an explanation in the README.

I'll try to take a pass at it later today, but I've been crazy busy.

**Comment by Bonitis** [comment]
Awesome! I will try to take a crack at a PR tomorrow morning. I agree that it shouldn't take a ton of code.

**Comment by Bonitis** [comment]
Turns out @mbifulco went and did it for me!

**Comment by deltaepsilon** [comment]
Big thanks to @Bonitis for the excellent suggestion and to @mbifulco for getting it done!
