### ISSUE TITLE
Error: Request error, retrying

### ISSUE THREAD

**Issue by Rajendra-Kumar** [deltaepsilon/firebase-search#8]
Elasticsearch WARNING: 2017-06-20T11:41:42Z
  Unable to revive connection: http://localhost:9200/

how to be connect elastic search with firebase .
Please Explain Starting to end.
how be defined in env.json

**Comment by deltaepsilon** [comment]
The REAME has the instructions:

https://github.com/deltaepsilon/firebase-search#configure-elasticsearch

It's likely that your problem is with Elasticsearch or the tunnel. First make sure that you can connect to Elasticsearch with your REST API. If you can't do that... the issue is your Elasticsearch install or your tunnel. If you've used App Launcher to start Elasticsearch, then the problem is likely your tunnel.

**Comment by Rajendra-Kumar** [comment]
I have install Elastic Search and run it localhost successfully.
please can you explain me about can we use Elastic search with firebase without Google Cloud billing project.
I have firebase project. can we use this project for elastic searching.

**Comment by deltaepsilon** [comment]
You'll need a paid project for Elasticsearch. The only free search of which I'm aware is Algolia, but you do need to be careful to add their branding to your search bar if you're on the free plan.

**Comment by Rajendra-Kumar** [comment]
ok . i have paid elastic search on firebase.
can you explain me paid elastic search also run on localhost or not?
where is run it?

**Comment by deltaepsilon** [comment]
You can run Elasticsearch remotely or on your local machine. For development purposes it can be nice to proxy a remote Elasticsearch node to your local machine... but it's not strictly necessary.

**Comment by Rajendra-Kumar** [comment]
how get server url for elastic search where is it run when elasticsearch paid or enable on firebase google cloud. please explain because i don't want to need local dowload elasticsearch.

**Comment by Rajendra-Kumar** [comment]
I have done this issue getting server url and used elasticsearch

**Comment by Rajendra-Kumar** [comment]
can you explain elastic search query for exact word matching and free text matching for a paragraph contain word on paragraph with filter range less than or grater than.

**Comment by deltaepsilon** [comment]
I'm sorry :(

I don't know much about Elasticsearch. I use Algolia these days.

**Comment by Rajendra-Kumar** [comment]
can you explain bulk data sync from firebase to Elasticsearch more than(300 record).
