### ISSUE TITLE
Support for Cloud Firestore

### ISSUE THREAD

**Issue by DahliaWitt** [deltaepsilon/firebase-search#9]
Looking at the code, it appears that this project only supports Firebase's realtime database. Will there be added support for the cloud firestore database type?

**Comment by deltaepsilon** [comment]
Nah. I've switched to Firestore along with everyone else, but now that we have Cloud Functions, syncing with Algolia is so easy that I don't use this lib any longer.

Here's an example of how I'm syncing one collection with Algolia on my latest project: [users-on-write.js](https://github.com/deltaepsilon/firebase-ssr-starter/blob/master/functions/src/users-on-write.js)

Now I copy/paste these functions around and change the paths a bit... but they're all about the same.
